import { createAudioPlayer, type AudioPlayer } from 'expo-audio';
import { useEffect } from 'react';
import { AppState } from 'react-native';

import { useGameStore, type UiPhase } from '../store/gameStore';
import { useProfileStore } from '../store/profileStore';
import { hostMusicVolume, registerClips, USE_AUDIO_HOST } from './audioHost';
import { configureAudioSession } from './sfx';

// Background music (generated by scripts/generate-music.mjs): a seamless loop, quieter
// behind the menus, louder during a run, silent while paused or in the background.
// On iOS and Android it loops in Web Audio (audioHost.tsx); the web build uses expo-audio.
const THEME = require('../../assets/music/theme.m4a');

if (USE_AUDIO_HOST) registerClips([{ name: 'music', source: THEME, volume: 1 }]);

let player: AudioPlayer | null = null;

function getPlayer(): AudioPlayer {
  if (!player) {
    configureAudioSession();
    player = createAudioPlayer(THEME);
    player.loop = true;
  }
  return player;
}

const VOLUME: Record<UiPhase, number> = {
  ready: 0.22,
  running: 0.4,
  paused: 0,
  revive: 0.15,
  over: 0.22,
  complete: 0.3,
};

function apply(enabled: boolean, phase: UiPhase, active: boolean): void {
  const volume = enabled && active ? VOLUME[phase] : 0;
  if (USE_AUDIO_HOST) {
    configureAudioSession();
    hostMusicVolume(volume);
    return;
  }
  const p = getPlayer();
  try {
    if (volume === 0) {
      p.pause();
      return;
    }
    p.volume = volume;
    p.play();
  } catch {
    // Audio problems must never affect the game.
  }
}

// Keeps the music in sync with the setting, the game phase and the app state.
export function useMusic(): void {
  const enabled = useProfileStore((s) => s.profile.settings.music);
  const hydrated = useProfileStore((s) => s.hydrated);
  const phase = useGameStore((s) => s.phase);

  useEffect(() => {
    if (!hydrated) return;
    apply(enabled, phase, AppState.currentState === 'active');
    const sub = AppState.addEventListener('change', (next) => {
      apply(enabled, phase, next === 'active');
    });
    return () => sub.remove();
  }, [enabled, phase, hydrated]);
}
