import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';

// Sound effects are generated by scripts/generate-sfx.mjs. Each sound gets a small pool of
// players so rapid repeats (coin streaks) don't cut each other off.
const SOURCES = {
  coin: require('../../assets/sfx/coin.wav'),
  jump: require('../../assets/sfx/jump.wav'),
  slide: require('../../assets/sfx/slide.wav'),
  lane: require('../../assets/sfx/lane.wav'),
  land: require('../../assets/sfx/land.wav'),
  powerup: require('../../assets/sfx/powerup.wav'),
  shield: require('../../assets/sfx/shield.wav'),
  boost: require('../../assets/sfx/boost.wav'),
  crash: require('../../assets/sfx/crash.wav'),
  click: require('../../assets/sfx/click.wav'),
  gameover: require('../../assets/sfx/gameover.wav'),
} as const;

export type SfxName = keyof typeof SOURCES;

const POOL_SIZE: Partial<Record<SfxName, number>> = { coin: 4, lane: 2, jump: 2, land: 2 };
const VOLUME: Partial<Record<SfxName, number>> = { lane: 0.5, land: 0.6, coin: 0.7 };

let players: Record<SfxName, AudioPlayer[]> | null = null;
const cursor: Partial<Record<SfxName, number>> = {};
let enabled = true;

export function initSfx(): void {
  if (players) return;
  // Respect the silent switch and let the player's own music keep playing.
  setAudioModeAsync({
    playsInSilentMode: false,
    interruptionMode: 'mixWithOthers',
    shouldPlayInBackground: false,
  }).catch(() => {});
  const created = {} as Record<SfxName, AudioPlayer[]>;
  for (const name of Object.keys(SOURCES) as SfxName[]) {
    const count = POOL_SIZE[name] ?? 1;
    created[name] = [];
    for (let i = 0; i < count; i++) {
      const p = createAudioPlayer(SOURCES[name]);
      p.volume = VOLUME[name] ?? 1;
      created[name].push(p);
    }
  }
  players = created;
}

export function setSfxEnabled(on: boolean): void {
  enabled = on;
}

export function playSfx(name: SfxName): void {
  if (!enabled || !players) return;
  const pool = players[name];
  const i = (cursor[name] ?? 0) % pool.length;
  cursor[name] = i + 1;
  const p = pool[i];
  try {
    p.seekTo(0);
    p.play();
  } catch {
    // A failed sound should never interrupt the game.
  }
}
